# Generated by Django 5.0.3 on 2024-04-22 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_user_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_Category',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
