# Generated by Django 5.0.3 on 2024-04-22 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_created_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_Order',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_OrderItem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='created_Product',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='created_Review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
