# Generated by Django 5.0.3 on 2024-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
