# Generated by Django 5.0.3 on 2024-04-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customer_email_alter_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
