# Generated by Django 5.0.3 on 2024-04-23 19:31

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_Order',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_Category',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_OrderItem',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_Product',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_Review',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_order',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
    ]
