# Generated by Django 5.0.3 on 2024-04-29 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_order_created_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Quản lý danh mục', 'verbose_name_plural': 'Quản lý danh mục'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Quản lý tài khoản', 'verbose_name_plural': 'Quản lý tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Quản lý đơn hàng', 'verbose_name_plural': 'Quản lý đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Quản lý giỏ hàng', 'verbose_name_plural': 'Quản lý giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Quản lý sản phẩm', 'verbose_name_plural': 'Quản lý sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Quản lý nhận xét', 'verbose_name_plural': 'Quản lý nhận xét'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên đăng nhập'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=200, verbose_name='Tên đăng nhập'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
    ]
