# Generated by Django 5.0.3 on 2024-05-01 23:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_payment_vnpay_remove_order_customer_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_vnpay',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Giá'),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='order_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='vnp_ResponseCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='vnp_TransactionNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
