# Generated by Django 5.0.3 on 2024-05-01 23:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_payment_vnpay_amount_payment_vnpay_order_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_vnpay',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='payment_vnpay',
            name='vnp_ResponseCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment_vnpay',
            name='vnp_TransactionNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
