# Generated by Django 5.0.3 on 2024-05-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_payment_vnpay_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_vnpay',
            options={'verbose_name': 'Hoá đơn', 'verbose_name_plural': 'Hoá đơn'},
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='product_list',
            field=models.TextField(blank=True, null=True, verbose_name='Danh sách sản phẩm'),
        ),
        migrations.AlterField(
            model_name='payment_vnpay',
            name='order_desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
