# Generated by Django 5.0.3 on 2024-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_payment_vnpay_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_vnpay',
            name='complete_pay',
            field=models.BooleanField(blank=True, default=False, verbose_name='Đã hoàn thành'),
        ),
    ]
